version: "3.6"
services:
  api-1:
    build:
      context: .
      dockerfile: "API/Dockerfile"
    ports:
    - "8071:80"
    volumes:
    - "C:/Users/nbruu/data/data:/data"
  web:
    build:
      context: .
      dockerfile: "API/Dockerfile"
    ports:
    - "8070:80"
