name: gitaction

on:
  push:
    branches: [ main, develop** ]
  pull_request_target:
    branches: [ main, develop ]

jobs:
  build:
    name: running unittest

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        
    
    - run: npm ci
    - run: npm run  build --if-present
    - run: npm test
